
const type = {
    CHANGE_STATE_PRODUCT_TYPE_COMBOBOX:"CHANGE_STATE_PRODUCT_TYPE_COMBOBOX",
    CHANGE_STATE_PRODUCT_BRAND_COMBOBOX:"CHANGE_STATE_PRODUCT_BRAND_COMBOBOX",
    CHANGE_STATE_SELLERS_COMBOBOX:"CHANGE_STATE_SELLERS_COMBOBOX",
    CHANGE_SELECTION_PRODUCT_TYPE_COMBOBOX:"CHANGE_SELECTION_PRODUCT_TYPE_COMBOBOX",
    CHANGE_SELECTION_PRODUCT_BRAND_COMBOBOX:"CHANGE_SELECTION_PRODUCT_BRAND_COMBOBOX",
    CHANGE_SELECTION_SELLERS_COMBOBOX:"CHANGE_SELECTION_SELLERS_COMBOBOX",
    CHANGE_INPUT_ITEM_SEARCHER:"CHANGE_INPUT_ITEM_SEARCHER",
    CHANGE_INPUT_DATE:"CHANGE_INPUT_DATE",
    CHANGE_INPUT_CHECKBOX_DATE:"CHANGE_INPUT_CHECKBOX_DATE"
}

export default type;